socket = "unix:///run/confidential-containers/cdh.sock"
[kbc]
name = "cc_kbc"
url = "http://10.88.0.1:18080"
[image]
max_concurrent_layer_downloads_per_image = 3
insecure_registry_hosts = ["10.88.0.1:19000"]
